spring:
  batch:
    job:
      names: ${job.name:NONE}
    #      enabled: false
    jdbc:
      initialize-schema: ALWAYS
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/web1
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 5251
  jpa:
    show-sql: true
